name: Mediathekview Updates
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1'

# Global environment variable accessible to all jobs and steps
env:
  MV_VERSION_FILE: 'mediathekview/docker/requirements.txt'

jobs:
  tag-new-versions:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout this repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    
    - name: Read the latest tag from repository Mediathekview
      id: mediathekview_remote
      uses: oprypin/find-latest-tag@e6d7a96b985a7dda6080e43e12771ad3a90fd389 # v1.1.0
      with:
        # The repository to scan.
        repository: mediathekview/MediathekView
        # We know that all relevant tags have a GitHub release for them.
        releases-only: false  
    
        
    - name: Read the locally stored version number
      id: mediathekview_local
      run: echo "version=$(cat $MV_VERSION_FILE)" >> $GITHUB_OUTPUT

    
    outputs:
      mv_local_version: ${{ steps.mediathekview_local.outputs.version }}
      mv_original_version: ${{ steps.mediathekview_remote.outputs.tag }}


  update-version:
    needs: tag-new-versions
    if: ${{ needs.tag-new-versions.outputs.mv_local_version != needs.tag-new-versions.outputs.mv_original_version }}
    runs-on: ubuntu-latest
    steps:

    - name: Set globals
      id: globals
      shell: bash
      run: |
        echo "NOW=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
        echo "MV_VERSION_FILE=$MV_VERSION_FILE" >> $GITHUB_OUTPUT


    - name: Checkout this repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1


    - name: Generate app token
      uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0 
      id: generate-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}


    - name: Write new version number to file
      run: echo "${{ needs.tag-new-versions.outputs.mv_original_version }}"  > $MV_VERSION_FILE
    

    - name: Create Pull Request for the change
      id: cpr
      uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
      with:
        token: ${{ steps.generate-token.outputs.token }}
        commit-message: Bump mediathekview/MediathekView in ${{ steps.globals.outputs.MV_VERSION_FILE }}
        signoff: false
        branch: dependabot-mediathekview-${{ needs.tag-new-versions.outputs.mv_original_version }}
        delete-branch: true
        title: 'Bump mediathekview/MediathekView from ${{ needs.tag-new-versions.outputs.mv_local_version }} to ${{ needs.tag-new-versions.outputs.mv_original_version }} in ${{ steps.globals.outputs.MV_VERSION_FILE }}'
        body: |
            Bump mediathekview/MediathekView from ${{ needs.tag-new-versions.outputs.mv_local_version }} to ${{ needs.tag-new-versions.outputs.mv_original_version }}.
        #    - Updated with *today's* date
        labels: |
          dependencies
        draft: false
        assignees: dwydler
