---
name: "Tools - Validate Dockerfile Schema"

"on":
  pull_request:
    branches:
      - "master"
    paths:
      - "**Dockerfile"

permissions:
  contents: read

jobs:
  validate-dockerfile-schema:
    name: Haskell Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Validate Dockerfile files
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5  # v3.3.0
        with:
          dockerfile: "Dockerfile"
          recursive: "true"
          ignore: "DL3008,DL3015"
